### ISSUE TITLE
범용 사고패턴에서의 오류

### ISSUE THREAD

**Issue by keisiki** [keisiki/TWKR-Textbung#10]
![캡처1](https://user-images.githubusercontent.com/70898529/95008940-ebed0580-0658-11eb-9056-7dad9d9d677c.JPG)

`RANDOM_PICK_T_SKILL`함수가
스킬번호를 1부터 2000까지 올리며 TALENTNAME:스킬번호+500의 검사를 돌리는데
TALENTNAME변수는 2000까지 할당되어있습니다
따라서 스킬번호가 1500을 넘으면 에러가 발생하는것으로 추정됩니다

아마 TALENTNAME의 한계를 조정하면 해결될것입니다

**Comment by keisiki** [comment]
![캡처1](https://user-images.githubusercontent.com/70898529/95009040-c3194000-0659-11eb-8408-9a73d500303f.JPG)
TALENTNAME과 TALENT의 한계를 2500까지 상향조정한 결과 또다른 오류가 발생합니다

**Comment by keisiki** [comment]
VARSIZE(SKILL_ARRY) -> VARSIZE("SKILL_ARRY")
VARSIZE 명령은 문자열을 받아야 했습니다

**Comment by SecretU4** [comment]
막 고치려고 컴퓨터를 켰는데 해결하셨다니 다행이네요. 제대로 작동 안하면 또 말씀해주세요.
