### ISSUE TITLE
XEraEmulator로 실행시 발생하는 컨피그 문제 해결

### ISSUE THREAD

**Issue by ValedictKR** [keisiki/TWKR-Textbung#14]
![emuera config](https://user-images.githubusercontent.com/35713925/97255711-93beb300-1854-11eb-86c9-46b5a5e0842e.jpg)
설정창에서 쇼부봐서 고쳐옴
뒤에 JPG만 딱 떼면 됨

**Comment by keisiki** [comment]
이미지 저장이 안뜸;

**Comment by keisiki** [comment]
컨피그 값이 내꺼랑 다른게 있어서 조금 수정해서 올려둠, 유저들을 위해서 선택권은 남겨두고 합쳐두겠음
