### ISSUE TITLE
탄막전투/스킬 관련 오타 제보

### ISSUE THREAD

**Issue by SecretU4** [keisiki/TWKR-Textbung#4]
`0001 문 라이트 레이.ERB`의 변수 선언 부분인 24행 부분에서 `속성` 변수를 `속성 = "마력"`과 같이 선언하셨던데, 이렇게 된 경우 `속성` 문자열 변수에 저장되는 값은 `마력`이 아닌 `"마력"`이기에 추후 문제가 생길 수 있어 보입니다.   
*emuera*에서의 변수 선언 형식에 따른 변수의 저장 양식은 다음과 같습니다.

| 선언 형식 | 저장 결과 |
| --- | --- |
| `변수 = 집` | `집` |
| `변수 = 집 ` | `집 ` |
| `변수 = "집"` | `"집"` |
| `변수 '= 집` | (`집`이라는 변수명을 가진 문자열 변수의 값 대응) |
| `변수 '= "집"` | `집` |

다른 부분은 확인해보지 못했으므로 참고해주시면 감사하겠습니다.

**Comment by keisiki** [comment]
C때 쓰던 버릇이 여기서...
속성은 문자열 반환을 해야하는 부분이 있기 때문에 고쳐야합니다
같은 함수의 "인수"의 경우엔 개발자만 괴롭기 때문에 상관없지만...
