### ISSUE TITLE
탄막승부에서의 예기치 않은 작동 오류

### ISSUE THREAD

**Issue by keisiki** [keisiki/TWKR-Textbung#8]
![캡처](https://user-images.githubusercontent.com/70898529/94998659-7f3d2100-05ee-11eb-85a7-364e658f507c.JPG)

_탄막 승부 시작시 내 턴이 강제 종료됨_

플레이어 턴 시작시 턴처리 변수 조작을 하는 구문이
`RESULT = 턴넘김`
으로 되어있었습니다
밑에 있는 IF문이 턴넘김 변수를 참조하는걸 보아
`턴넘김 = RESULT`
가 맞습니다

![캡처1](https://user-images.githubusercontent.com/70898529/94998674-9aa82c00-05ee-11eb-9d19-0e2e09dd247e.JPG)

_적 턴에 내가 나를 공격함_

![캡처2](https://user-images.githubusercontent.com/70898529/94998682-b0b5ec80-05ee-11eb-85ec-cf55b22b6107.JPG)

_내 턴의 공격 커맨드의 대상이 나임_

![캡처3](https://user-images.githubusercontent.com/70898529/94998706-de029a80-05ee-11eb-9e2a-3716e4f50688.JPG)

_내 턴에 스킬 시전시 대상이 나로 지정됨_

상기 두 이슈는 해결했습니다

@T_턴처리 함수의 
`ARG = T_턴주인
ARG:1 = T_턴반대`
는 반대가 되어서

`T_턴주인 = ARG 
T_턴반대 = ARG:1`
가 되어야 했습니다

![캡처4](https://user-images.githubusercontent.com/70898529/94998716-f672b500-05ee-11eb-94e6-83cd32ae539c.JPG)
_AI가 간혹 행동하지 않음, 이 부분은 본인이 덜 작성한게 잘못일거임 아마도_

_전체적으로 봤을때 턴주인이나 턴 반대가 이상하게 꼬인듯 함_
버그가 사라짐, 아마 위에 턴 반대 턴 주인 처리를 고침으로써 해결된 듯

이외에

**적 턴에 AI가 회피를 연속 시전할시 방어력이 계속해서 증가하는 오류**

AI의 행동 패턴 조정도 중요하겠지만 회피 커맨드가 회피 플래그를 인식하지 않는다는점이 있음
 이 부분도 본인이 덜 작성한게 잘못일거임 아마도

**그런데 턴이 지나도 플레이어와 적의 회피가 해제되지 않음**

버프 감소처리에 오류가 있는것으로 추정됨

![캡처1](https://user-images.githubusercontent.com/70898529/94998818-9defe780-05ef-11eb-9c6b-5cec88d3ce77.JPG)
エラー内容：文字列変数に数値型は代入できません
_임시로 AI 패턴중 스킬 시전 패턴이 들어간 상태임_

_이는 타입(공격형)이 문자열이 아니라 #DIM CONST로 지정된 상수 이기 때문임_
_(뉴탄막전투변수.ERH의 69~72행)_

해결함
해당 행을 주석처리했음

**Comment by SecretU4** [comment]
`@T_SKILL`(스킬의 상수 정보 불러옴)에서 ARG로 사용자를 불러오는 이유가 인터럽트 실행을 위해서라고 하셨는데, 정확히 어떤 경우인지 예시를 들어서 말씀해주실 수 있으신가요? 잘 와닫지가 않아서요.

**Comment by SecretU4** [comment]
그리고 `#DIM`시 사용하는 `DYNAMIC`은 처음에 해당 사용자 변수를 `+`나 `-` 등을 사용하지 않고 `=`로 해당하는 값을 바로 지정하면(`FOR`문도 마찬가지) 이전 저장된 값을 덮어써버리기 때문에 없어도 되는 경우가 꽤 됩니다.(`@버프감소처리`의 사용자 변수라던지)

**Comment by keisiki** [comment]
인터럽트 호출의 예로

2중 효과를 지닌 패시브등을 만들수 있습니다
캐릭터 a가 공격 행위를 취할때 50퍼센트 확률로
(5*지성)피해를 입히는 패시브 스킬의 예가 있습니다


이러한 스킬은 추후 대전 승리시 플레이어도 습득가능하므로 target으로 대체할수 없습니다

또는 사망시 일정 확률로 15*인내만큼 회복하는 스킬도 있습니다

이 스킬은 턴 엔드시에 발생하는 도트 데미지에도 발동해야하는데

턴 엔드시엔 턴 주인이 항상 target입니다

이때 arg를 받으면 복잡한 처리없이 바로 효과를 적용할수있습니다

또한 2번째 인수라 안써도 작동하므로 큰 상관은 없습니다

턴엔드시 상태이상 감소를 하게 한 이유는

상태이상 효과 테스트중 의도한 경우와 다른 양상이 보였기 때문입니다

실명 상태이상을 내 턴에 1턴 걸었을때 의도는 이번 상대 공격에 실명 효과가 적용되는겁니다

다만 이전 방식의 경우 턴처리시 상태이상이 감소되어 상대턴 시작시 상태이상이 소멸합니다

그렇다고 2턴 실명을 걸으면 상태이상창에 실명이 2턴 걸렸다고 나오는데
이는 사용자가 혼란을 느낄수도 있으므로 변동한것입니다

**Comment by keisiki** [comment]
dim dynamic의 경우는 기억은 안나지만 아마 회피의 방어력 무한대 증가를 해결하기 위해 변수를 비워보는 작업용으로 해본것일겁니다

**Comment by SecretU4** [comment]
현재 코드상으로 `@T_턴처리`를 호출할 때마다 첫번째 인자를 `T_턴주인`으로, 두번째 인자를 `T_턴반대`로 교대하고 있기 때문에 `MASTER`, `TARGET`과는 상관없이 해당 스킬이 호출될 때의 시전자가 `T_턴주인`이고 그 상대가 `T_턴반대`이기 때문에  `TARGET`으로 대체할 필요가 없습니다.  

당장 제가 손본 1번이나 2번 스킬쪽을 보시면 피해량 적용 공식이 `T_턴주인`의 지성값입니다. 이걸 `T_턴반대`로 하면 상대방의 지성값을 기반한 공식으로 바꿀 수도 있고요.  

모코우 패시브 같은 스킬은 구현할 때 스킬로 구현할 것인가 개별 캐릭터 관련 사고패턴을 만들때 적용할 것인가의 문제가 있긴 하겠지만(스킬로 구현하면 해당 스킬을 호출하기 전까진 적용이 안될테니) 구현한다면 버프 효과로 구현한 다음 턴종료시마다 같이 적용시키면 됩니다. `TCVAR` 번호 만들어놓은걸 보면 아시겠지만 지속시간 관련 변수는 상태이상이랑 버프가 연결되어 있기 때문에 상태이상 관련 처리 함수에서 버프를 같이 처리할 수도 있습니다. 따로 만들어놓으셨길래 임의로 빼둔거거든요.

**Comment by SecretU4** [comment]
그리고 `@T_턴엔드`에서도 `T_턴주인`과 `T_턴반대` 각각 `@ONGOING_T_SKILL` 처리와 `@상태이상감소처리` 처리를 하고 있습니다. 구현하신 것을 보니 `@버프감소처리`는 `T_턴처리`에서 하고 있긴 하던데, 이건 계산 좀 해서 `@상태이상감소처리` 에 합칠 수 있으면 합치면 되는 문제고요.

**Comment by keisiki** [comment]
1번은 냅두기로 하고

2번에 대해선 
플레이어턴에 적의 체력이 0이 되면 적턴이 되기전에 패배처리가 우선되지 않나요?
여기에 굳이 버프 추가처리를 하는것보다 그냥 0이되는 순간 시스템체크에서 실행시키는게 나을것 같습니다


그리고 arg등의 변수를 꾸역꾸역 넣는것은 템플릿의 작성을 할때 최소한의 작업으로도 짤수있게 해서 아이디어가 있는 사람들이 쉽게참여할수 있게 하려는겁니다


그래서 변수처리를 한곳에서 몰아서 했던거고요

**Comment by SecretU4** [comment]
`.ERH`를 통해 전역변수를 만드신 것을 보았기에 오히려 ARG로 만들 경우 혼란이 올 수 있어 말씀드린 것입니다.
이미 `T_턴주인`과 `T_턴반대`로 해당 스킬이 호출될 때의 호출 주체와 그 상대값이 저장되어 있는데 ARG값을 써버린다면 그다지 효과가 없을 것 같아서요.

**Comment by SecretU4** [comment]
그리고 시스템체크에서 그런 기합의띠 같은 기능을 넣는 것은 찬성합니다. 승부처리 앞에서 미리 시스템체크를 돌리면 되겠네요.

**Comment by keisiki** [comment]
단적으로 말하자면 제가 헷갈려서 입니다;
시전주체는 a이고 계수도 a껄 쓰는데 발동타이밍은 b의 턴이니 턴 반대를 쓰다가 제가 실수할까봐입니다

**Comment by keisiki** [comment]
헌데 지금 회피 버프가 정상적으로 해제가 되고 있지 않는 에러가 있는데 버프 감소처리로 봤을때 제대로 문제를 못찾겠습니다.
혹시 확인해 주시겠어요?

**Comment by SecretU4** [comment]
제가 버프감소 함수에서 버프를 잘못 적었네요. 지금 만져둔게 좀 많긴 할텐데 이거 수정한거 포함해서 같이 병합 리퀘 올릴테니 확인해보시고 또 바꿔본 탬플릿이 익숙해지기 어려우시다면 해당 부분 커밋만 빼고 다시 올리겠습니다.
